### ISSUE TITLE
无法识别扩展

### ISSUE THREAD

**Issue by wyh3130024630** [BDFFZI/XUnity.AutoTranslator.TencentTranslate#1]
BepInEx Xunity5.3/5.2
dll加入文件夹，写好配置文件，但没有识别到扩展

**Comment by BDFFZI** [comment]
应该不是BepInEx和XUnity5.3的问题，我这边试了一下是没问题。

![image](https://github.com/BDFFZI/XUnity.AutoTranslator.TencentTranslateEndpoint/assets/50945880/8e443687-1efd-4f97-a4b9-e037c306145a)

**Comment by wyh3130024630** [comment]
BepInEx\plugins\XUnity.AutoTranslator\Translators
放在这里没错吧
之前腾讯api有点问题用不了，但我用别的翻译器调腾讯api会有报错，我去控制台弄了下现在腾讯api能用了，但你这里还是识别不了。
在Config.ini里强行指定
```
[Service]
Endpoint=TencentTranslate
```
进去也是变成---

**Comment by wyh3130024630** [comment]
好吧 我的问题 beplnex安装出了问题，框架没加载
