### ISSUE TITLE
大佬，新版dll,用不了，可以更新一下吗

### ISSUE THREAD

**Issue by fredsk** [BDFFZI/XUnity.AutoTranslator.TencentTranslate#2]
旧版的dll文件可以用，但是有多余的单词“UsedAmount"。新版的腾讯dll用不了，没有翻译

**Comment by BDFFZI** [comment]
你说的新版旧版啥意思？是因为COM3D2的汉化补丁来的吗？我刚刚已经测试了这个DLL，腾讯翻译是可以正常运行的（但没放在XUnity.Translator中，而是单独测试的代码）。

**Comment by BDFFZI** [comment]
我懂了，你是说能翻译但每个翻译结果后面都有一个”UsedAmount“是吧，我晚上会修复这个问题，到时候你再下载新版本的DLL就行。

**Comment by ParanoiaIsGreat** [comment]
牛啊老哥，我试过deepseek插件，能用但翻译太慢了，还马上要涨价了，目前还是这个最好用

**Comment by fredsk** [comment]
> 我懂了，你是说能翻译但每个翻译结果后面都有一个”UsedAmount“是吧，我晚上会修复这个问题，到时候你再下载新版本的DLL就行。

谢谢大佬，腾讯api终于可以用上了，只因百度api太少了。我是用xunity翻译欧美unity游戏来的
